### PR TITLE
.travis.yml does not cache dependencies

### PR DESCRIPTION
**Pull request by YunLemon**
Travis CI can cache content that does not often change, to speed up your build process.

### CODE REVIEW

**Comment by iamazy** [comment]
Thanks for the corrections  :)

**Comment by iamazy** [comment]
I wonder why commiter of this pr became me ? @YunLemon

**Comment by YunLemon** [comment]
I haven't be concerned about this problems. Maybe because you create a new commit to merge this pr?

**Comment by iamazy** [comment]
I haven't add any commit for this pr, I'm just a little curious haha, Thanks again

**Pull request merged**
